### ISSUE TITLE
Improve Cart Page Layout

### ISSUE THREAD

**Issue by suryanshsingh2001** [suryanshsingh2001/MyLibrary#8]
---
# Issue: Improve Cart Page Design/Frontend

**Description:**

The current design and user interface of the cart page require improvements to enhance the user experience. The cart page may not be visually appealing, user-friendly, or efficient in its current state.

**Tasks:**

- [ ] Review the existing cart page design and layout.
- [ ] Identify areas for improvement in terms of visual aesthetics and user interaction.
- [ ] Implement design enhancements and improvements to the cart page frontend.
- [ ] Ensure the cart page is responsive and functions smoothly on various screen sizes.
- [ ] Test the changes to verify that the cart page now provides an improved user experience.
- [ ] Change the button color scheme to a more UI friendly scheme.

**Additional Information:**

A well-designed cart page can significantly impact user satisfaction and the overall usability of the application. Enhancing the cart page's frontend will contribute to a more polished and user-friendly MyLibrary experience.
![image](https://github.com/suryanshsingh2001/MyLibrary/assets/80690023/aa25058b-9621-4bca-af27-0aba58752350)

**Get Assigned:**

If you are interested in working on this issue or have any questions, please leave a comment below, and we'll assign the task to you.

Let's make the cart page visually appealing and user-friendly! 🛒✨

**Comment by waleedkhano** [comment]
@suryanshsingh2001  can i work on this?

**Comment by suryanshsingh2001** [comment]
@waleedkhano I have assigned the issue. Make sure to share the screenshots. You can start working on it. Happy Coding 🧑‍💻

**Comment by waleedkhano** [comment]
@suryanshsingh2001 can you please guide that how can i connect the backend locally ?

**Comment by suryanshsingh2001** [comment]
Sure,
## Google Books API Key Setup

1. Visit the [Google Developers Console](https://console.developers.google.com/).
2. Create a new project or select an existing one.
3. Navigate to the "APIs & Services" > "Credentials" section.
4. Click on the "Create Credentials" button and select "API Key."
5. Your API key will be generated. Click on "Restrict Key" to configure usage restrictions if desired.
6. Copy the generated API key.

## Auth0 API Keys Setup

1. Visit the [Auth0 Dashboard](https://auth0.com/dashboard/).
2. Log in to your Auth0 account or sign up if you don't have one.
3. Create a new Auth0 application:
   - Go to the "Applications" section.
   - Click on "Create Application."
   - Choose "Single Page Web Applications."
   - Configure the settings as needed.
   - Save your changes.
4. Navigate to the "Settings" tab of your Auth0 application.
5. Copy the "Domain" and "Client ID."

Add these api keys into your  `.env` into the `client` folder.
Your .env may look this

```
VITE_REACT_APP_GOOGLEBOOK_API_KEY=YOUR_GOOGLEBOOK_API_KEY

VITE_REACT_APP_AUTH0_DOMAIN=YOUR_AUTH0_DOMAIN
VITE_REACT_APP_AUTH0_CLIENT_ID=YOUR_AUTH0_CLIENT_ID
```

**Comment by suryanshsingh2001** [comment]
In case you are not able to access the auth0 authentication.
Copy the code and paste it into local clone of the repo.
https://gist.github.com/suryanshsingh2001/f89973b3f3d826b60f6426796a5063f7
This is will let accesss the cart functionality.

**Make sure to add the old file back to the repo and then make an PR**.
